Table office {
  office_id integer [PK]
  telephone integer
  size integer
}

Table salesperson{
  salesperson_id integer [PK]
  name varchar
  commission_percentage decimal
  year_of_hire integer

  office_id integer [unique, Ref: ?- office.office_id]
  customer_id integer [unique]
}

Table sells {
  sells_id integer [pk]
  salesperson_id integer [not null]
  product_id integer [not null]

}

Table product {
  product_id integer [PK]
  name varchar
  price decimal
}

Table customer {
  customer_id integer [pk]
  name varchar
  HQ_city varchar
}

Table customer_employee {
  employee_id integer [pk]
  name varchar
  title varchar

  customer_id integer [not null]
}

Ref: salesperson.customer_id -? customer.customer_id
Ref: sells.salesperson_id > salesperson.salesperson_id
Ref: sells.product_id > product.product_id
Ref: customer_employee.customer_id > customer.customer_id




