Table users {
  user_id integer [pk]
  username varchar
  email varchar [unique]
  privacy_level varchar
  notification_pref varchar
  theme_color varchar
}

Table user_social_links {
  user_id integer
  social_link varchar

  indexes {
    (user_id, social_link) [pk]
  }
}

Table communities {
  comm_id integer [pk]
  description text
}

Table joins {
  join_id integer [pk]
  user_id integer [not null]
  comm_id integer [not null]
  join_date timestamp
}

Table posts {
  post_id integer [pk]
  user_id integer [not null]
  content text
  timestamp timestamp
}

Table comments {
  comment_no integer
  post_id integer
  text text
  post_time timestamp

  indexes {
    (post_id, comment_no) [pk]
  }
}

Ref: users.user_id <? user_social_links.user_id
Ref: users.user_id <? posts.user_id
Ref: posts.post_id <? comments.post_id
Ref: users.user_id <? joins.user_id
Ref: communities.comm_id < joins.comm_id